site_name: Kai Lang
pages:
    - Install: install.md
    - The Basics: index.md
    - Types:
        - Basic Types: types/basic.md
        - Arrays: types/array.md
        - Pointers: types/pointer.md
        - Enumerations: types/enumeration.md
        - Unions: types/union.md
        - Structures: types/struct.md
        - Type Definition: types/type-def.md
    - Operators: operator.md
    - Control Flow: control-flow.md
    - Procedures: procedure.md
    - Import and Modules: module.md
    - Compile Time Execution: compile-time.md
    - Entry Point: entry-point.md
    - Working with C: c.md
extra_css:
    - css/extra.css
theme: material
markdown_extensions:
    - codehilite
    - admonition
repo_url: https://github.com/kai-language/docs
repo_name: Kai-Lang